import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private categories: Category[] = [
    { id: 1, name: 'Фитнес' },
    { id: 2, name: 'Умные гаджеты' },
    { id: 3, name: 'Аксессуары' },
    { id: 4, name: 'Восстановление' },
  ];

  private products: Product[] = [
    {
      id: 1,
      name: 'Беговая дорожка Sport&Fitness SF-TMBr-004 электрическая',
      description: 'Основные характеристики: Складная конструкция: Легко складывается, экономя место в вашем доме. Тип: Электрическая беговая дорожка с мощным двигателем 2.0 л.с., обеспечивающая плавную и эффективную работу. Максимальный вес пользователя: Подходит для пользователей весом до 150 кг.',
      price: 241836,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pba/pd4/84570788.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/begovaja-dorozhka-sport-fitness-sf-tmbr-004-elektricheskaja-128173898/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 2,
      name: 'Креатин Qazprotein Creatine Monohydrate нейтральный 300 г',
      description: 'Особенности: 100% Халяльный продукт.  Микронизирован до минимальной фракции. Без вкуса и запаха.Фармацевтическое качество.  Очищен от остаточных включений. Чистый продукт: не содержит углеводов. Соответствует стандартам ISO 22000 и HACCP.',
      price: 7940,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p34/p63/107809770.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/kreatin-qazprotein-creatine-monohydrate-neitral-nyi-300-g-100388127/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 3,
      name: 'Набор гантелей разборная 30 кг',
      description: 'Этот комплект предлагает разнообразие возможностей для тренировки различных групп мышц. Этот набор гантелей позволит вам эффективно тренироваться дома, меняя нагрузку в зависимости от ваших целей и уровня подготовки. Гантели идеально подходят для различных упражнений на руки, плечи, грудь и спину.',
      price: 14499,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p60/pf0/50743207.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/nabor-gantelei-razbornaja-30-kg-121329589/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 4,
      name: 'Наколенник GF SPORT Support 0835 черный',
      description: 'Особенности: Анатомическая конструкция — идеально повторяет форму колена, обеспечивая свободу движений. Универсальный размер — подходит для большинства пользователей, легко регулируется. Дышащие материалы — хлопок и эластан обеспечивают комфорт даже при длительном использовании.',
      price: 677,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/he1/hd1/86427465744414.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/gf-sport-support-0835-chernyi-105667120/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 5,
      name: 'Налокотник FASHION 86310 черный универсальный',
      description: 'Особенности: Универсальный размер — подходит для большинства пользователей. Эластичный материал — обеспечивает свободу движений и отличную посадку. Дышащая ткань — предотвращает перегрев и обеспечивает комфорт в любых условиях.',  
      price: 594,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h97/h1f/81393517789214.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/fashion-86310-chernyi-universal-nyi-110971614/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 6,
      name: 'Смарт-часы Apple Watch SE GPS Gen.2 2024 S/M 40 мм бежевый',
      description: 'Мощные датчики для информации о вашем здоровье и активности. Инновационные функции безопасности. Удобные способы оставаться на связи. Более быстрый двухъядерный процессор для повышенной производительности.',
      price: 139900,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p55/p9b/5542335.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/apple-watch-se-gps-gen-2-2024-s-m-40-mm-bezhevyi-129172890/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 7,
      name: 'Умная колонка Яндекс Станция Мини 3 фиолетовый',
      description: 'Яндекс Станция Мини 3 — новое поколение самой популярной умной колонки с Алисой, которая поможет продуктивно работать, вести домашние дела и классно отдыхать. Впервые виртуальный ассистент №1* научился понимать и выполнять сразу две команды.',
      price: 44572,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p0b/p2c/57956178.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/jandeks-stantsija-mini-3-fioletovyi-131778294/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 8,
      name: 'Смартфон Apple iPhone 17 Pro 256Gb оранжевый',
      description: 'Apple iPhone 17 Pro 256Gb — это воплощение инноваций и стиля, сочетающее в себе непревзойденную производительность, потрясающую камеру и яркий OLED-дисплей. Особенности: Устойчивое к царапинам стекло — сохранит экран в идеальном состоянии.',
      price: 827892,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p18/p96/64168413.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/apple-iphone-17-pro-256gb-oranzhevyi-145467625/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 9,
      name: 'Робот-пылесос Roborock Q8 Max Pro Plus Q8MPP02-02 белый',
      description: 'Робот-пылесос Roborock Q8 Max Pro Plus — умное решение для эффективной уборки вашего дома, сочетающее в себе влажную и сухую уборку, высокую мощность всасывания и инновационные технологии. Особенности: Мощность всасывания 10000 Па — идеальная чистота на любых поверхностях.',
      price: 169990,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p16/pe0/42281333.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/roborock-q8-max-pro-plus-q8mpp02-02-belyi-139667064/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 10,
      name: 'Смарт-очки Ray-Ban Meta Wayfarer Standard RW4006 601SM1 50-22 черный',
      description: 'Высококачественные линзы доступны в солнцезащитных, поляризационных линзах или линзах Transitions. Все линзы обеспечивают повышенную прозрачность, комфорт и 100% защиту от UVA и UVB лучей. Снимайте фотографии и видео с помощью новой сверхширокоугольной камеры с разрешением 12 МП и системы из пяти микрофонов.',
      price: 277388,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pef/pd8/54777416.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/smart-ochki-ray-ban-meta-wayfarer-standard-rw4006-601sm1-50-22-chernyi-116509833/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 11,
      name: 'Шарф кашемир 180 x 70 см',
      description: 'Шарф из кашемира – это изысканный аксессуар, который сочетает в себе нежность и тепло. Он имеет длинную форму, позволяющую завязывать его различными способами. Шарф изготовлен из мягкой и натуральной шерсти кашемира, что придает ему невероятную мягкость и теплоту.',
      price: 1295,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h5b/ha8/84255439585310.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/sharf-17344455-657898-kashemir-180-sm-x-70-sm-113986560/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 12,
      name: 'Сумка кросс-боди Michael Kors канвас коричневый',
      description: 'Особенности: 100% оригинал — гарантированное качество от известного бренда. Кожаный ремень и цепь — надёжные и стильные элементы для удобства ношения. Канвас — прочный и лёгкий материал, который легко чистится.',
      price: 50654,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h76/h7d/85313554087966.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/sumka-kross-bodi-michael-kors-35s1gttc9b-kanvas-korichnevyi-102116795/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 13,
      name: 'Солнцезащитные очки FashionLab овальные поляризованные',
      description: 'Особенности: Стильный и современный дизайн — подчеркните свою индивидуальность. Универсальная посадка — комфортно сидят на переносице. Высокая защита от солнца — обеспечьте своим глазам надёжный комфорт. Качество по стандартам ЕС и США — долговечность и безопасность.',
      price: 53000,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pa3/p40/86820814.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/solntsezaschitnye-ochki-fashionlab-twig-x-f-l-yoko-c1-oval-nye-poljarizovannye-108225646/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 14,
      name: 'Складной зонт LUCCI полуавтомат красный',
      description: 'Цвет : красный; Тип зонта : складной; Механизм складывания зонта : полный автомат; автомат; Диаметр купола зонта (см) : 104 см; Длина зонта в сложенном виде (см) : 30 см; Материал ручки зонта : пластик; soft touch',
      price: 64175,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pd7/p64/53361292.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/skladnoi-zont-lucci-d75f1455c307ed72-poluavtomat-krasnyi-142618231/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 15,
      name: 'Ремень натуральная кожа 90 см черный',
      description: 'Элегантный женский ремень из натуральной кожи станет превосходным дополнением любому наряду. Этот кожаный аксессуар идеально подходит для платья юбки, также джинсов брюк, создавая завершенный образ. Широкий размерный ряд позволяет выбрать оптимальный вариант под различные типы телосложения',
      price: 50590,
      rating: 4.8,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pf1/pa5/109242096.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/remen-817645297-natural-naja-kozha-90-sm-chernyi-158065241/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 16,
      name: 'Массажер Fascial Gun MP-01 ручной перкуссионный',
      description: 'Это физиотерапевтический пистолет, который улучшает общее здоровье мягких тканей тела и предотвращает воспаление, вызванное спайками между фасцией и мышцами. 6 сменных массажные головки и 30 регулируемых уровней скорости.',
      price: 11000,
      rating: 4.7,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pae/p95/104867830.png?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/massazher-fascial-gun-mp-01-ruchnoi-perkussionnyi-106061601/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 17,
      name: 'Диффузор Gamma DORO Энергия океана 55 мл',
      description: 'Наполните свой дом свежестью и прохладой с помощью аромадиффузора с палочками "Энергия океана" от GAMMA DORO. Парфюм для дома с прохладным бризом и свежестью волн с еле уловимыми нотками морской соли и водорослей заряжает бодростью и энергией необъятной стихии.',
      price: 2400,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p16/pa0/21954920.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/gamma-d-oro-energija-okeana-55-ml-110347729/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 18,
      name: 'Массажер DJM ProLuxe A-1 напольный 3D-массаж, надавливающий, разминающий, разогревающий, шиацу, компрессионный',
      description: 'Глубокий массаж для полного расслабления. Шиацу-массаж стоп – ролики мягко разминают ступни, улучшая кровообращение. Компрессионный массаж – воздушные подушки обеспечивают лимфодренаж, устраняя отеки. Прогрев с углеродными волокнами',
      price: 112500,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pce/p2d/61852483.jpeg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/massazher-djm-proluxe-a-1-napol-nyi-3d-massazh-nadavlivajuschii-razminajuschii-razogrevajuschii-shiatsu-kompressionnyi-135627034/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 19,
      name: 'Energy Oats Vita Saumal капсулы 90 шт',
      description: 'Особенности: 90 капсул в упаковке - длительный курс применения для достижения результата. Без ГМО и сахара - забота о вашем здоровье без лишних добавок. Поддержка энергии и бодрости - помогает справляться с усталостью и стрессом.',
      price:  14900,
      rating: 4.9,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/pb7/pfb/17666576.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/energy-oats-vita-saumal-kapsuly-90-sht-132723114/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 20,
      name: 'Свеча для медитации Павлишина 40-200 200 шт',
      description: 'Особенности: Цилиндрическая форма — удобно использовать в любых условиях. Время горения 2 часа — достаточно для полноценной медитации. Натуральный воск — безопасен для здоровья и окружающей среды.',
      price:  9346,
      rating: 5.0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h71/h5d/67731335512094.jpg?format=gallery-medium',
      link: 'https://kaspi.kz/shop/p/svecha-dlja-meditatsii-pavlishina-40-200-200-sht-108375848/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getProductsByCategory(categoryId: number): Product[] {
  return this.products.filter(p => p.categoryId === categoryId);
  }
  removeProduct(productId: number) {
  this.products = this.products.filter(p => p.id !== productId);
  }
}